create database legalos;

CREATE TABLE IF NOT EXISTS legalos.education
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    school character varying(255) NOT NULL,
    study character varying(255) NOT NULL,
    start_date character varying(50) NOT NULL,
    end_date character varying(50) ,
    resume_key character varying(255)  NOT NULL
);

CREATE TABLE IF NOT EXISTS legalos.languages
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    language_name character varying(255) ,
    resume_key character varying(255) ,
    CONSTRAINT launguages_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS legalos.personal_information
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    first_name character varying(255) ,
    last_name character varying(255) ,
    email character varying(255) ,
    phone character varying(20) ,
    language character varying(50) ,
    profile_summary text ,
    resume_key character varying(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS legalos.resume_extracted_data
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    file_name character varying(255) ,
    creation_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    resume_key character varying(255) ,
    CONSTRAINT resume_extracted_data_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS legalos.skills
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) NOT NULL,
    resume_key character varying(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS legalos.work_experience
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    title character varying(255) NOT NULL,
    company character varying(255) NOT NULL,
    start_date character varying(50) NOT NULL,
    end_date character varying(50) ,
    description text ,
    resume_key character varying(255) NOT NULL
);